services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_WS_URL=${VITE_WS_URL}
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - battle-wordle-network
    restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - DB_PATH=${DB_PATH}
      - PROJECT_ROOT=/app
    networks:
      - battle-wordle-network
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /etc/letsencrypt:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
      - server
    networks:
      - battle-wordle-network
    restart: always

networks:
  battle-wordle-network:
    driver: bridge