version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      - VITE_WS_URL=ws://battlewordle.app/ws
    networks:
      - battle-wordle-network
    restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - battle-wordle-network
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
      - server
    networks:
      - battle-wordle-network
    restart: always

networks:
  battle-wordle-network:
    driver: bridge 