services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      - VITE_WS_URL=wss://battlewordle.app/ws  # Note: changed to wss:// for secure WebSocket
    networks:
      - battle-wordle-network
    restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - battle-wordle-network
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
      - server
    networks:
      - battle-wordle-network
    restart: always

networks:
  battle-wordle-network:
    driver: bridge